services:
  - type: worker
    env: node
    name: resend-welcome-drip-campaign
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: REPLY_TO_EMAIL
        sync: false